version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: javax.measure:unit-api
    versions:
    - 2.1.1
  - dependency-name: tech.units:indriya
    versions:
    - 2.1.1
